export default function TermsPage() {
  return (
    <main style={styles.container}>
      <article style={styles.card}>
        <h1 style={styles.title}>Terms of Service</h1>
        <p style={styles.effective}>Effective date: July 1, 2026</p>

        <p style={styles.paragraph}>
          RoomKit is operated by{" "}
          <strong>[PLACEHOLDER: Your Legal Entity Name]</strong>, based in{" "}
          <strong>[PLACEHOLDER: State]</strong>. By creating an account or using
          RoomKit, you agree to these terms.
        </p>

        <Section title="What RoomKit Is">
          <p style={styles.paragraph}>
            RoomKit is an AI-powered room design tool. Given your room type,
            style preferences, and budget, it generates a curated set of real,
            purchasable products with live buy links and a running total that
            stays within your budget. RoomKit is a product discovery and
            shopping tool &mdash; not professional interior design advice.
          </p>
        </Section>

        <Section title="Account Requirements">
          <ul style={styles.list}>
            <li style={styles.li}>You must be 13 years of age or older to create an account.</li>
            <li style={styles.li}>You must provide a valid email address.</li>
            <li style={styles.li}>You are responsible for keeping your login credentials secure.</li>
            <li style={styles.li}>One account per person. Automated account creation is not permitted.</li>
          </ul>
        </Section>

        <Section title="How You May Use RoomKit">
          <p style={styles.paragraph}>
            RoomKit is for personal, non-commercial use. You may not:
          </p>
          <ul style={styles.list}>
            <li style={styles.li}>Scrape, crawl, or programmatically access RoomKit</li>
            <li style={styles.li}>Resell or redistribute designs generated by RoomKit</li>
            <li style={styles.li}>Attempt to reverse-engineer the design pipeline or product ranking algorithms</li>
            <li style={styles.li}>Use RoomKit to generate content that is illegal, harmful, or deceptive</li>
          </ul>
        </Section>

        <Section title="AI-Generated Content">
          <p style={styles.paragraph}>
            Room renders (images) are generated by AI and are provided for
            visualization purposes only. They are approximate representations of
            how selected products might look in a room &mdash; actual products may
            differ in color, scale, or appearance. Renders are not architectural
            drawings, blueprints, or professional design plans.
          </p>
          <p style={styles.paragraph}>
            Product recommendations are generated by AI based on your style
            preferences and budget. RoomKit does not guarantee that any
            recommended product will meet your specific needs, fit your space, or
            match the render exactly.
          </p>
        </Section>

        <Section title="Products and Pricing">
          <p style={styles.paragraph}>
            RoomKit displays products from third-party retailers. Product
            prices, availability, and specifications are sourced from retailer
            data and may change at any time. The price shown in your design is
            the price at the time of generation &mdash; the actual price at
            checkout may differ. RoomKit is not responsible for price changes,
            product availability, or the accuracy of retailer product listings.
          </p>
        </Section>

        <Section title="Affiliate Disclosure">
          <p style={styles.paragraph}>
            RoomKit is a participant in the Amazon Services LLC Associates
            Program, an affiliate advertising program. Product buy links contain
            our affiliate tag. When you click a link and make a purchase on
            Amazon, we may earn a commission at no additional cost to you. This
            commission helps fund the service.
          </p>
          <p style={styles.paragraph}>
            Affiliate relationships do not influence which products are
            recommended. Product selection is driven by style matching, budget
            fit, and specification requirements &mdash; not by commission rates.
          </p>
        </Section>

        <Section title="Third-Party Links">
          <p style={styles.paragraph}>
            Buy links take you to Amazon.com or other third-party retailers. Once
            you leave RoomKit, the retailer&apos;s own terms of service and
            privacy policy apply. RoomKit is not responsible for third-party
            websites, their products, shipping, returns, or customer service.
          </p>
        </Section>

        <Section title="Your Data">
          <p style={styles.paragraph}>
            Your designs, interaction data, and account information are handled
            as described in our{" "}
            <a href="/privacy" style={styles.link}>Privacy Policy</a>. You can
            delete your account and all associated data at any time from the{" "}
            <a href="/account" style={styles.link}>Account page</a>.
          </p>
        </Section>

        <Section title="Disclaimers">
          <ul style={styles.list}>
            <li style={styles.li}>
              RoomKit is provided &quot;as is&quot; without warranties of any kind.
            </li>
            <li style={styles.li}>
              We do not guarantee uninterrupted or error-free service.
            </li>
            <li style={styles.li}>
              AI-generated recommendations and renders are approximations, not
              professional advice.
            </li>
            <li style={styles.li}>
              We are not responsible for purchasing decisions you make based on
              RoomKit&apos;s recommendations.
            </li>
          </ul>
        </Section>

        <Section title="Account Termination">
          <p style={styles.paragraph}>
            You may delete your account at any time. We may suspend or terminate
            accounts that violate these terms, engage in abusive behavior, or
            create excessive load on the service. If we terminate your account,
            we will delete your data as described in the{" "}
            <a href="/privacy" style={styles.link}>Privacy Policy</a>.
          </p>
        </Section>

        <Section title="Changes to These Terms">
          <p style={styles.paragraph}>
            If we make material changes, we will update the effective date at the
            top of this page. Continued use of RoomKit after a change constitutes
            acceptance of the updated terms.
          </p>
        </Section>

        <Section title="Governing Law">
          <p style={styles.paragraph}>
            These terms are governed by the laws of the state of{" "}
            <strong>[PLACEHOLDER: State]</strong>. Any disputes will be resolved
            in the courts of <strong>[PLACEHOLDER: State/County]</strong>.
          </p>
        </Section>

        <Section title="Contact">
          <p style={styles.paragraph}>
            Questions about these terms? Email{" "}
            <strong>[PLACEHOLDER: legal@yourdomain.com]</strong>.
          </p>
        </Section>

        <a href="/" style={styles.backLink}>Back to RoomKit</a>
      </article>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={styles.section}>
      <h2 style={styles.sectionTitle}>{title}</h2>
      {children}
    </section>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    background: "#f8f7f4",
    fontFamily: "'DM Sans', sans-serif",
    padding: "60px 20px",
  },
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: "2.5rem 2rem",
    width: "100%",
    maxWidth: 720,
    boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
    alignSelf: "flex-start",
  },
  title: {
    fontFamily: "'DM Serif Display', serif",
    fontSize: "1.8rem",
    margin: 0,
    color: "#1a1a1a",
  },
  effective: {
    color: "#888",
    fontSize: "0.85rem",
    marginTop: 4,
    marginBottom: 32,
  },
  section: {
    marginBottom: 28,
  },
  sectionTitle: {
    fontFamily: "'DM Serif Display', serif",
    fontSize: "1.15rem",
    color: "#1a1a1a",
    marginBottom: 8,
    marginTop: 0,
  },
  paragraph: {
    color: "#444",
    fontSize: "0.9rem",
    lineHeight: 1.65,
    margin: "0 0 12px",
  },
  list: {
    margin: "0 0 12px",
    paddingLeft: 20,
  },
  li: {
    color: "#444",
    fontSize: "0.9rem",
    lineHeight: 1.65,
    marginBottom: 6,
  },
  link: {
    color: "#1a1a1a",
    fontWeight: 600,
  },
  backLink: {
    display: "block",
    textAlign: "center" as const,
    marginTop: 32,
    color: "#888",
    fontSize: "0.85rem",
    textDecoration: "none",
  },
};
